---
kind: pipeline
type: docker
name: test

steps:
  - name: install prerequisites
    image: node:14.8.0-alpine
    volumes:
      - name: deps
        path: /node_modules
    commands:
      - yarn install
    when:
      branch:
        - develop

  - name: test build
    image: node:14.8.0-alpine
    volumes:
      - name: deps
        path: /node_modules
    commands:
      - yarn build
      - yarn generate
    when:
      branch:
        - develop

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: deployment

steps:
  - name: copy important files to host
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      key:
        from_secret: ssh_key
      port: 22
      target: /wwwroot/jessequinn
      source:
        - docker-compose.yaml
        - api/Dockerfile
        - api/.dockerignore
        - api/.env.prod
        - api/go.mod
        - api/go.sum
        - api/configs/*
        - api/internal/*
        - api/pkg/*
        - api/cmd/
        - frontend/*
#      strip_components: 1 # remove api/
      rm: true
    when:
      branch:
        - master

  - name: build and start docker on host
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      key:
        from_secret: ssh_key
      port: 22
      script:
        - (cd /wwwroot/golang-ldap-interface && cp api/.env.prod .env)
        - (cd /wwwroot/golang-ldap-interface && cat frontend/.env.prod >> .env)
        - (cd /wwwroot/golang-ldap-interface && docker-compose build)
        - (cd /wwwroot/golang-ldap-interface && docker-compose stop)
        - (cd /wwwroot/golang-ldap-interface && docker-compose up -d)
    when:
      branch:
        - master

depends_on:
  - test

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request


