---
kind: pipeline
type: docker
name: test

steps:
#  - name: test build
#    image: node:14.8.0-alpine
#    commands:
#      - yarn install
#      - yarn build

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 134.122.44.112
      username: root
      port: 22
      key:
        from_secret: ssh_key
      script:
        - sed -i 's/\(jessequinn:\)\(.*\)/\1${DRONE_COMMIT_SHA:0:7}"/' /root/nomad/jobs/jessequinn.nomad
        - nomad job run -address=http://10.118.0.3:4646 jessequinn.nomad

trigger:
  branch:
    - develop
  event:
    - push
    - pull_request
---
kind: pipeline
type: docker
name: deployment

steps:
  - name: build and publish app
    image: plugins/docker
    settings:
      username:
        from_secret: repository_username
      password:
        from_secret: repository_password
      repo: damasu/jessequinn
      dockerfile: Dockerfile
      context: .
      target: prod
      build_args:
        VERSION: 14
        PORT: 3000
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 134.122.44.112
      username: root
      port: 22
      key:
        from_secret: ssh_key
      script:
        - sed -i 's/\(jessequinn:\)\(.*\)/\1${DRONE_COMMIT_SHA:0:7}"/' /root/nomad/jobs/jessequinn.nomad
        - nomad job run -address=http://10.118.0.3:4646 jessequinn.nomad

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
