---
kind: pipeline
type: docker
name: test

steps:
  - name: install prerequisites
    image: node:14.8.0-alpine
    volumes:
      - name: deps
        path: /node_modules
    commands:
      - yarn install
    when:
      branch:
        - develop

  - name: test build
    image: node:14.8.0-alpine
    volumes:
      - name: deps
        path: /node_modules
    commands:
      - yarn build
      - yarn generate
    when:
      branch:
        - develop

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: deployment

steps:
  - name: install prerequisites
    image: node:14.8.0-alpine
    volumes:
      - name: deps
        path: /node_modules
    commands:
      - yarn install
    when:
      branch:
        - develop

  - name: build
    image: node:14.8.0-alpine
    volumes:
      - name: deps
        path: /node_modules
      - name: dist
        path: /dist
    commands:
      - yarn build
      - yarn generate
    when:
      branch:
        - develop

  - name: copy dist
    image: appleboy/drone-scp
    volumes:
      - name: dist
        path: /dist
    settings:
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password
      port: 22
      target: /wwwroot/jessequinn
      source:
        - /dist/*
      rm: true
    when:
      branch:
        - develop

volumes:
  - name: deps
    temp: {}
  - name: dist
    temp: {}

depends_on:
  - test

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request


