#---
#kind: pipeline
#type: docker
#name: test
#
#steps:
#  - name: install prerequisites
#    image: node:14.8.0-alpine
#    volumes:
#      - name: deps
#        path: /node_modules
#    commands:
#      - yarn install
#    when:
#      branch:
#        - develop
#
#  - name: test build
#    image: node:14.8.0-alpine
#    volumes:
#      - name: deps
#        path: /node_modules
#    commands:
#      - yarn build
#      - yarn generate
#    when:
#      branch:
#        - develop
#
#volumes:
#  - name: deps
#    temp: {}
#
#trigger:
#  branch:
#    - master
#    - develop
#  event:
#    - push
#    - pull_request

#---
kind: pipeline
type: docker
name: deployment

steps:
  - name: build
    image: node:14.8.0-alpine
    volumes:
      - name: cache
        path: /dist
    commands:
      - yarn install
      - yarn build
      - cp -r dist/* /dist
    when:
      branch:
        - develop

  - name: build and publish app
    image: plugins/docker
    settings:
      username:
        from_secret: repository_username
      password:
        from_secret: repository_password
      repo: damasu/jessequinn
      dockerfile: Dockerfile
      context: .
      target: prod
      build_args:
        VERSION: 14
        PORT: 3000
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - master
        - develop
volumes:
  - name: cache
    temp: {}

#depends_on:
#  - test

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request
